# Generated by Django 2.0.7 on 2018-08-01 21:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20180801_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='metin',
            field=ckeditor.fields.RichTextField(verbose_name='Metin'),
        ),
    ]
